name: Test
on:
  push:
    paths:
      - "src/**.rs"
  pull_request:
    paths:
      - "src/**.rs"

jobs:  
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: 1.68.0

      - name: Check out code
        uses: actions/checkout@v3

      - name: Run tests
        run: cargo test